Traceback (most recent call last):
  File "/home/andretelfer/anaconda3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/andretelfer/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/andretelfer/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/andretelfer/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/andretelfer/anaconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/andretelfer/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/andretelfer/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/andretelfer/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
for k in [1, 5, 10, 0, 3]:
    print(1/k)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mZeroDivisionError[0m                         Traceback (most recent call last)
Input [0;32mIn [10][0m, in [0;36m<cell line: 1>[0;34m()[0m
[1;32m      1[0m [38;5;28;01mfor[39;00m k [38;5;129;01min[39;00m [[38;5;241m1[39m, [38;5;241m5[39m, [38;5;241m10[39m, [38;5;241m0[39m, [38;5;241m3[39m]:
[0;32m----> 2[0m     [38;5;28mprint[39m([38;5;241;43m1[39;49m[38;5;241;43m/[39;49m[43mk[49m)

[0;31mZeroDivisionError[0m: division by zero
ZeroDivisionError: division by zero

